Filters
git-voo/slu_reuse pull request #24
Opened 2024-10-20 22:54 UTC by nlp-saiteja

Integrated MongoDB database with Node.js backend.
Rendered data from backend to frontend using Axios for asynchronous data fetching.
Utilized Thunder Client in VS Code for API testing and integration.
Implemented filtering features such as:
Category filtering
Search functionality
Location-based filtering
Sorting by newest/oldest.
Embedded a "Contact Us" form at the bottom of the landing page
Created test cases following Test Driven Development

2024-10-21 18:53 UTC, shagunsharmaslu requested changes
I have let a few comments on a few files. Lets connect if you have any doubts on my comments.

2024-10-21 18:53 UTC, shagunsharmaslu commented on frontend/src/components/navigation/index.js
I want to understand why are you hardcoding locations?

2024-10-22 04:33 UTC, nlp-saiteja commented on frontend/src/components/navigation/index.js
For this sprint, we're using hardcoded dummy data to ensure that the filter functionality operates correctly with the existing data from MongoDB. In the next sprint, we can extend the item model to include a city field, allowing for dynamic population of location data. This will be sourced directly from the "Manage Listing" feature, ensuring that the dropdown reflects actual locations associated with the items stored in the database.

2024-10-22 04:37 UTC, nlp-saiteja commented on .vscode/settings.json
I hadn't noticed that; it was an extension in VS Code that got committed by mistake.

2024-10-22 14:28 UTC, merged